### PR TITLE
fix aws ssh issue

### LINKED ISSUE #442: gardenctl ssh <aws_node> fails with `InvalidParameterValue`
**Describe the bug**
`gardenctl ssh <aws_node>` fails with `InvalidParameterValue` (using `gardenctl/gctl-aws` cluster)

**To Reproduce**
Using 52235f2f with a test cluster gives:

```
$ go run cmd/gardenctl/main.go ssh ip-XXXX.eu-west-1.compute.internal 

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Security Group exists sg-0f4274271179c8402 skipping creation.

(3/4) Creating bastion host and node host security group
Bastion Host exists, skipping creation.
2020/11/13 10:16:47 AWS CLI failed with
An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block /32 is malformed

exit status 254
exit status 1
```

Using just the nostname: 

```
$ go run cmd/gardenctl/main.go ssh ip-XXXX

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
2020/11/13 09:25:29 AWS CLI failed with
An error occurred (InvalidParameterValue) when calling the DescribeSecurityGroups operation: vpc-id

exit status 254
exit status 1
```

**Gardenctl Version (please complete the following information):**
 - Version/Commit 52235f2f

### PR DESCRIPTION
**Pull request by neo-liang-sap**
**What this PR does / why we need it**:
fix aws ssh issue
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/442

**Special notes for your reviewer**:
1) in my env, `nc -vtnz ip port` returns sth like `127.0.0.1 49269 open` so the result should grep `open`, instead of `succeed`
not sure my `nc` is correct one
```
nc --version                                               (ccee-m3/default)
netcat (The GNU Netcat) 0.7.1
Copyright (C) 2002 - 2003  Giovanni Giacobbi

This program comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of this program under the terms of
the GNU General Public License.
For more information about these matters, see the file named COPYING.

Original idea and design by Avian Research <hobbit@avian.org>,
Written by Giovanni Giacobbi <giovanni@giacobbi.net>.
```

2) fix a small typo, `shh` to `ssh`

3) when bastion exist, `a.BastionPrivIP` and `a.BastionIP` should also be assigned with values (like what they are treat in non bastion exist path) , otherwise following step will fail due to these two properties empty

**Release note**:
```improvement operator
fix aws ssh issue
```

### CODE REVIEW

**Comment by neo-liang-sap** [comment]
testing result
image

**Review by dansible — DISMISSED** [review]

File: pkg/cmd/ssh_aws.go [hunk 1]
```diff
@@ -242,7 +246,7 @@ func (a *AwsInstanceAttribute) sshPortCheck() {
 		cmd := exec.Command("bash", "-c", ncCmd)
 		output, _ := cmd.CombinedOutput()
 		fmt.Println("=>", string(output))
-		if strings.Contains(string(output), "succeeded") {
+		if strings.Contains(string(output), "open") {
```
Comment (dansible) [inline pkg/cmd/ssh_aws.go:249]: This should be `succeeded`. 

With `open`, I get:

```
Bastion host instance running.
Opened SSH Port on Node.
Waiting 60 seconds for Bastion SSH port open
=> Connection to ... port 22 [tcp/*] succeeded!

=> Connection to ... port 22 [tcp/*] succeeded!

=> Connection to ... port 22 [tcp/*] succeeded!

=> Connection to ... port 22 [tcp/*] succeeded!

=> Connection to ... port 22 [tcp/*] succeeded!

=> Connection to ... port 22 [tcp/*] succeeded!

	SSH Port Open on Bastion TimeOut
(4/4) Cleanup
Cleaning up bastion host configurations...
```

With `succeeded`:
```
Bastion host instance running.
Opened SSH Port on Node.
Waiting 60 seconds for Bastion SSH port open
=> Connection to ... port 22 [tcp/*] succeeded!

Opened SSH Port on Bastion
SSH gardener@... => gardener@ip-...compute.internal
Warning: Permanently added '...' (ED25519) to the list of known hosts.
Warning: Permanently added 'ip-....compute.internal' (ED25519) to the list of known hosts.
(4/4) Cleanup
Cleaning up bastion host configurations...
```

**Review by dansible — CHANGES_REQUESTED** [review]

File: pkg/cmd/ssh_aws.go (hunk 1 above)
Comment (petersutter) [inline pkg/cmd/ssh_aws.go:249]: instead of `sshPortCheck()`, can't we reuse the newly introduced [function]?(https://github.com/gardener/gardenctl/pull/445/files#diff-8a970d51dea43e926c0b913c26887464b362c5f723fb1d740a5a07d428434c07R355) 
```go
func CheckIPPortReachable(ip string, port string) error 
```

Comment (neo-liang-sap) [reply pkg/cmd/ssh_aws.go]: thanks @petersutter , i add retry logic in `CheckIPPortReachable` function and use it here

Comment (neo-liang-sap) [reply pkg/cmd/ssh_aws.go]: Hi @dansible , i used a newly introduced function `CheckIPPortReachable` which is using native go code (so we don't have dependency on different version of binary like your nc returns succeeded but mine returns open) to perform ssh port check

Comment (petersutter) [reply pkg/cmd/ssh_aws.go]: that's what I was asking in the other PR https://github.com/gardener/gardenctl/pull/445#discussion_r525999141
> and this works without having to dial/try multiple times within a certain amount of time?

File: pkg/cmd/utils.go [hunk 2]
```diff
@@ -349,17 +349,22 @@ func PrintoutObject(objectToPrint interface{}, writer io.Writer, outputFormat st
...
+		conn, err := net.DialTimeout("tcp", net.JoinHostPort(ip, port), timeout)
+		if err != nil {
+			fmt.Println("Connecting error:", err)
+		}
+		if conn != nil {
+			defer conn.Close()
+			fmt.Printf("IP %s port %s is reachable\n", ip, port)
+			return nil
+		}
+		time.Sleep(time.Second * 10)
```
Comment (petersutter) [inline pkg/cmd/utils.go:366]: why is there a need to sleep 10 seconds?

File: pkg/cmd/utils.go [hunk 3]
```diff
@@ -349,17 +349,22 @@ func PrintoutObject(objectToPrint interface{}, writer io.Writer, outputFormat st
 	return nil
 }
 
-//CheckIPPortReachable check whether IP with port is reachable with 1 min
+//CheckIPPortReachable check whether IP with port is reachable with 2 min
```
Comment (petersutter) [inline pkg/cmd/utils.go:352]:
```suggestion
//CheckIPPortReachable check whether IP with port is reachable within 2 min
```

File: pkg/cmd/utils.go [hunk 4]
```diff
@@ -349,17 +349,22 @@ func PrintoutObject(objectToPrint interface{}, writer io.Writer, outputFormat st
...
-	if conn != nil {
-		defer conn.Close()
-		fmt.Printf("IP %s port %s is reachable\n", ip, port)
-		return nil
+	attemptCnt := 0
+	for attemptCnt < 6 {
+		timeout := time.Second * 10
+		conn, err := net.DialTimeout("tcp", net.JoinHostPort(ip, port), timeout)
+		if err != nil {
+			fmt.Println("Connecting error:", err)
```
Comment (petersutter) [inline pkg/cmd/utils.go:359]: Either omit the error as long as you are retrying or add a hint in case another try is made

File: pkg/cmd/ssh_aws.go (hunk 1 above)
Comment (neo-liang-sap) [reply pkg/cmd/ssh_aws.go]: yes, previously i though it was working as retry but later i found it's not, so i added the logic

File: pkg/cmd/utils.go (hunk 3 above)
Comment (neo-liang-sap) [reply pkg/cmd/utils.go]: thanks, i fixed the typo

File: pkg/cmd/utils.go (hunk 4 above)
Comment (neo-liang-sap) [reply pkg/cmd/utils.go]: thanks, i omitted the error

File: pkg/cmd/utils.go (hunk 2 above)
Comment (neo-liang-sap) [reply pkg/cmd/utils.go]: thanks, i removed this line

**Comment by neo-liang-sap** [comment]
build failed due to https://github.com/gardener/gardenctl/issues/455 ,

**Comment by petersutter** [comment]
> build failed due to #455 ,

How could this even happen in the first place, that code slips into `master` that produces build errors?

**Comment by neo-liang-sap** [comment]
> #455

it's very wired - code is in https://github.com/gardener/gardenctl/pull/431 which has all CI check passed.... but actually this PR has some errors...i've notified PR owner to fix this

image

**Comment by neo-liang-sap** [comment]
all check passed after https://github.com/gardener/gardenctl/issues/455 is fixed , @petersutter could you please review this PR when you have time? thanks!
-Neo

File: pkg/cmd/utils.go [hunk 5]
```diff
@@ -349,17 +349,18 @@ func PrintoutObject(objectToPrint interface{}, writer io.Writer, outputFormat st
...
-	timeout := time.Second * 60
-	conn, err := net.DialTimeout("tcp", net.JoinHostPort(ip, port), timeout)
-	if err != nil {
-		fmt.Println("Connecting error:", err)
-	}
-	if conn != nil {
-		defer conn.Close()
-		fmt.Printf("IP %s port %s is reachable\n", ip, port)
-		return nil
+	attemptCnt := 0
```
Comment (petersutter) [inline pkg/cmd/utils.go:354]: nit: would rather name it attemptCount or just attempt.

**Review by petersutter — APPROVED** [review]
/lgtm
feel free to also change the variable name as suggested.

**Review by dansible — APPROVED** [review]
