### PR TITLE
fix logic covering both garden+seed+shoot and garden+project+shoot

### LINKED ISSUE #295: gardenctl `aws|gcp...` rely that project will be targeted
**Describe the bug**
`gardenctl` expects that project will be targeted in cmd/operate.go
https://github.com/gardener/gardenctl/blob/master/pkg/cmd/operate.go#L47 

In this way if `gardenctl aws ...` is called and the Path to the shoot is constructed by using its seed, the command will fail with
```
projects.core.gardener.cloud "<seed-name>" not found
```

**To Reproduce**
g target garden... -> g target seed... -> g target shoot ...

**Expected behavior**
It should also expect that the Target can be constructed using `seed` instead of `project`

### PR DESCRIPTION
**Pull request by neo-liang-sap**
**What this PR does / why we need it**:
current operate.go only covers scenario when target stack is garden+project+shoot, should also cover scenario garden+seed+shoot
**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/gardenctl/issues/295

**Special notes for your reviewer**:
/CC @Kristian-ZH 
**Release note**:
```improvement operator
Fix operate.go missing coverage on scenario garden+seed+shoot
```

### CODE REVIEW

**Comment by neo-liang-sap** [comment]
the test covers following flow:
1) gardenctl target -g xxx -s xxx -t xxx (garden target is garden+seed+shoot), then `gardenctl aws ec2 xxx ` works fine
2) gardenctl target -g xxx -p xxx -t xxx (garden target is garden+project+shoot), then `gardenctl aws ec2 xxx ` works fine

@Kristian-ZH i hope i'm understanding correctly on your issue, do let me know if i missed anything, thanks!

**Comment by Kristian-ZH** [comment]
Yup, this will resolve the issue.

Thanks!

**Review by Kristian-ZH — APPROVED** [review]
/lgtm

File: pkg/cmd/operate.go [hunk 1]
```diff
@@ -43,11 +43,28 @@ func operate(provider, arguments string) {
...
+		project, err := gardenClientset.CoreV1beta1().Projects().Get(target.Stack()[1].Name, metav1.GetOptions{})
+		checkError(err)
+		shoot, err = gardenClientset.CoreV1beta1().Shoots(*project.Spec.Namespace).Get(target.Stack()[2].Name, metav1.GetOptions{})
+		checkError(err)
+	} else if target.Stack()[1].Kind == "seed" {
+		shootList, err := gardenClientset.CoreV1beta1().Shoots("").List(metav1.ListOptions{})
+		checkError(err)
+		var filteredShoots []gardencorev1beta1.Shoot
+		for _, s := range shootList.Items {
+			if s.Name == target.Stack()[2].Name {
```
Comment (petersutter) [inline pkg/cmd/operate.go:57]: @neo-liang-sap  sorry for beeing late for the review, but here you are missing the check for the seed. Do not add to `filteredShoots` if the seed does not match the one on the target stack

Comment (neo-liang-sap) [reply pkg/cmd/operate.go:57]: thanks! i added a new PR for this [here](https://github.com/gardener/gardenctl/pull/298)
