### PR TITLE
Handle properly hibernated Shoots

### LINKED ISSUE #135: Improvements around hibernation
1. `g info` currently only shows number of Shoots per Seed. It is frequently used it to check how many Shoots are hosted on the Seed. Along with the total count, a good improvement would be to add the count of currently hibernated and running Shoot control planes to get a better overview.

```
$ g info
Garden: foo
Shoots:
  total: 5
  unscheduled: 0
  aws-us3:
    active: 3
    hibernated: 2
```

2. `g shell` could be hibernation aware. Currently it shows an `EOF` error:

```
$ g target shoot hibernated-one
$ g shell
Error: Get $HOST/api/v1/nodes: EOF
```

It could show a better error message such as:

```
$ g shell
Error: shoot "hibernated-one" is hibernated
```

### Definition of done
- [x] 1. `g info` to show hibernated Shoots.
- [x] 2. `g shell` to handle properly hibernated Shoots

### PR DESCRIPTION
**Pull request by KristianZH**
**What this PR does / why we need it**:
1) Show hibernated shoots on `gardenctl ls shoots` and `gardenctl info` command.
2)  Handle properly hibernated Shoots for `gardenctl shell`

**Which issue(s) this PR fixes**:
Fixes #135

**Special notes for your reviewer**:
@ialidzhikov @DockToFuture 

**Release note**:

```improvement operator
`gardenctl info` does now show also the number of hibernated Shoots per Seeds. `gardenctl ls shoots` now also list whether the Shoot is hibernated.
```

### CODE REVIEW

**Comment by DockToFuture** [comment]
Thank you for the PR, the feature looks pretty nice. Can we also the total number of hibernated shoots to the output of the ```gardenctl info``` cmd?

**Comment by DockToFuture** [comment]
Do you also want to add the other two points from #135  to the PR as @ialidzhikov has suggested?

**Comment by KristianZH** [comment]
> Can we also the total number of hibernated shoots to the output of the gardenctl info cmd?
Yup, will add it.

> Do you also want to add the other two points from #135 to the PR as @ialidzhikov has suggested?

Okay i can rename this PR as WIP for now and to bind it to #135

File: pkg/cmd/shell.go [hunk 1]
```diff
@@ -59,8 +60,28 @@ func NewShellCmd(reader TargetReader, ioStreams IOStreams) *cobra.Command {
 			if client, err = target.K8SClient(); err != nil {
 				return err
 			}
+
+			gardenClientset, err := target.GardenerClient()
+			checkError(err)
```
Comment (ialidzhikov) [inline pkg/cmd/shell.go]:
```suggestion
			if err != nil {
				return err
			}
```

File: pkg/cmd/shell.go [hunk 2]
```diff
@@ -59,8 +60,28 @@ func NewShellCmd(reader TargetReader, ioStreams IOStreams) *cobra.Command {
...
+			var shoot *gardencorev1alpha1.Shoot
```
Comment (ialidzhikov) [inline pkg/cmd/shell.go]: This code fragment below is duplicated across the project several times - for example in ssh.go. Can we extract the code fragment to prevent duplication?

File: pkg/cmd/shell.go [hunk 3]
```diff
@@ -73,12 +94,17 @@ func NewShellCmd(reader TargetReader, ioStreams IOStreams) *cobra.Command {
 }
 
 // printNodes print all nodes in k8s cluster
-func printNodes(client kubernetes.Interface, ioStreams IOStreams) (err error) {
+func printNodes(client kubernetes.Interface, ioStreams IOStreams, shoot *gardencorev1alpha1.Shoot) (err error) {
+	if shoot.Status.IsHibernated {
+		fmt.Fprintln(ioStreams.Out, "The current shoot is hibernated")
```
Comment (ialidzhikov) [inline pkg/cmd/shell.go]:
```suggestion
		return fmt.Errorf("shoot %q is hibernated", shoot.Name)
```

File: pkg/cmd/ssh.go [hunk 4]
```diff
@@ -138,9 +137,15 @@ func getSSHKeypair(shoot *gardencorev1alpha1.Shoot) *v1.Secret {
 }
 
 // printNodeNames print all nodes in k8s cluster
-func printNodeNames(kindIP string) {
+func printNodeNames(kindIP string, shoot *gardencorev1alpha1.Shoot) {
+	if shoot.Status.IsHibernated {
+		fmt.Println("The current shoot is hibernated")
```
Comment (ialidzhikov) [inline pkg/cmd/ssh.go]:
```suggestion
		return fmt.Errorf("shoot %q is hibernated", shoot.Name)
```

File: pkg/cmd/utils.go [hunk 5]
```diff
@@ -181,3 +183,30 @@ func ValidateClientConfig(config clientcmdapi.Config) error {
...
+func FetchShootFromTarget(target TargetInterface) (*gardencorev1alpha1.Shoot, error) {
+	gardenClientset, err := target.GardenerClient()
+	if err != nil {
+		return nil, err
+	}
+
+	var shoot *gardencorev1alpha1.Shoot
+	if target.Stack()[1].Kind == "project" {
+		project, err := gardenClientset.CoreV1alpha1().Projects().Get(target.Stack()[1].Name, metav1.GetOptions{})
+		checkError(err)
```
Comment (ialidzhikov) [inline pkg/cmd/utils.go]:
```suggestion
		if err != nil {
			return nil, err
		}
```

File: pkg/cmd/utils.go [hunk 6]
```diff
@@ -181,3 +183,30 @@ func ValidateClientConfig(config clientcmdapi.Config) error {
...
+		shoot, err = gardenClientset.CoreV1alpha1().Shoots(*project.Spec.Namespace).Get(target.Stack()[2].Name, metav1.GetOptions{})
+		checkError(err)
```
Comment (ialidzhikov) [inline pkg/cmd/utils.go]:
```suggestion
		if err != nil {
			return nil, err
		}
```

File: pkg/cmd/utils.go [hunk 7]
```diff
@@ -181,3 +183,30 @@ func ValidateClientConfig(config clientcmdapi.Config) error {
...
+	} else {
+		shootList, err := gardenClientset.CoreV1alpha1().Shoots("").List(metav1.ListOptions{})
+		checkError(err)
```
Comment (ialidzhikov) [inline pkg/cmd/utils.go]:
```suggestion
		if err != nil {
			return nil, err
		}
```

File: pkg/cmd/utils.go [hunk 8]
```diff
@@ -181,3 +183,30 @@ func ValidateClientConfig(config clientcmdapi.Config) error {
...
+	}
+
+	var shoot *gardencorev1alpha1.Shoot
+	if target.Stack()[1].Kind == "project" {
+		project, err := gardenClientset.CoreV1alpha1().Projects().Get(target.Stack()[1].Name, metav1.GetOptions{})
+		checkError(err)
+		shoot, err = gardenClientset.CoreV1alpha1().Shoots(*project.Spec.Namespace).Get(target.Stack()[2].Name, metav1.GetOptions{})
+		checkError(err)
+	} else {
+		shootList, err := gardenClientset.CoreV1alpha1().Shoots("").List(metav1.ListOptions{})
```
Comment (ialidzhikov) [inline pkg/cmd/utils.go]:
```suggestion
		shootList, err := gardenClientset.CoreV1alpha1().Shoots(metav1.NamespaceAll).List(metav1.ListOptions{})
```

File: pkg/cmd/ssh.go [hunk 9]
```diff
@@ -138,12 +122,19 @@ func getSSHKeypair(shoot *gardencorev1alpha1.Shoot) *v1.Secret {
 }
 
 // printNodeNames print all nodes in k8s cluster
-func printNodeNames(kindIP string) {
+func printNodeNames(kindIP string, shoot *gardencorev1alpha1.Shoot) (err error) {
```
Comment (ialidzhikov) [inline pkg/cmd/ssh.go]: The kindIP arg seems unused, can we remove it?
```suggestion
func printNodeNames(shoot *gardencorev1alpha1.Shoot) (err error) {
```

File: pkg/cmd/ssh.go [hunk 10]
```diff
@@ -138,12 +122,19 @@ func getSSHKeypair(shoot *gardencorev1alpha1.Shoot) *v1.Secret {
...
+	if shoot.Status.IsHibernated {
+		return fmt.Errorf("shoot %q is hibernated", shoot.Name)
+	}
+
 	machines := getMachines().Items
```
Comment (ialidzhikov) [inline pkg/cmd/ssh.go]: You can pass the Shoot name to `getMachines` to prevent reading it once again from the target.

File: pkg/cmd/info.go [hunk 11]
```diff
@@ -47,14 +47,23 @@ func NewInfoCmd(targetReader TargetReader, ioStreams IOStreams) *cobra.Command {
 				return err
 			}
 
-			var unscheduled = 0
-			shootsCountPerSeed := make(map[string]int)
+			var (
+				unscheduled                  = 0
+				hibernatedShootsCount        = 0
+				shootsCountPerSeed           = make(map[string]int)
```
Comment (ialidzhikov) [inline pkg/cmd/info.go]:
```suggestion
				totalShootsCountPerSeed           = make(map[string]int)
```

File: pkg/cmd/shell.go [hunk 12]
```diff
@@ -73,17 +84,21 @@ func NewShellCmd(reader TargetReader, ioStreams IOStreams) *cobra.Command {
 }
 
 // printNodes print all nodes in k8s cluster
-func printNodes(client kubernetes.Interface, ioStreams IOStreams) (err error) {
+func printNodes(client kubernetes.Interface, ioStreams IOStreams, shoot *gardencorev1alpha1.Shoot) (err error) {
```
Comment (ialidzhikov) [inline pkg/cmd/shell.go]:
```suggestion
func printNodes(client kubernetes.Interface, shoot *gardencorev1alpha1.Shoot, ioStreams IOStreams) (err error) {
```

**Comment by ialidzhikov** [comment]
With #138, gardenctl no longer calls the Shoot kube-apiserver to get the nodes. So the hibernation check here is no longer needed.
