### PR TITLE
Fix target cmd for shoots with duplicating names

### LINKED ISSUE #104: Target cmd failed when 2 shoots have a same name
**Describe the bug**
Target cmd currently cannot distinguish a shoot cluster when multiple shoots have the same name even if they are in different projects.
This could be a bug in target.go targetShoot() where all the shoots with the same name will be appended to the list despite the seed/project they belong to.

**To Reproduce**
1. Create 2 shoot clusters with the same name
2. `gardenctl target <landscape>` -> `gardenctl target <project>` -> `gardenctl target <shoot>`
3. Even if project is targeted, `Multiple shoots found` and `Target a project first` are still shown and the target cmd will fail. 

**Expected behavior**
Target cmd should work when multiple shoot clusters have the same name.

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. b21b4bde14663faee381697cb1d93a8b53a3e81a]

**Additional context**

### PR DESCRIPTION
**Pull request by ialidzhikov**
**What this PR does / why we need it**:
- Fix target cmd for shoots with duplicating names
- Move commands under `pkg/cmd`

**Which issue(s) this PR fixes**:
Fixes #104 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Target command now properly handles cases when there are multiple shoots with the same name across different projects.
```

### CODE REVIEW

File: pkg/cmd/target.go [hunk 1]
```diff
@@ -115,11 +112,11 @@ func NewTargetCmd(targetReader TargetReader, targetWriter TargetWriter, configRe
 				} else if len(shoots) == 1 {
 					targetShoot(targetWriter, shoots[0])
 				} else if len(shoots) > 1 {
-					fmt.Println("shoots:")
-					for _, val := range shoots {
-						fmt.Println("- shoot: " + val)
+					fmt.Fprintln(ioStreams.Out, "shoots:")
+					for _, shoot := range shoots {
+						fmt.Fprintln(ioStreams.Out, "- project: "+shoot.Namespace)
```
Comment (DockToFuture) [inline pkg/cmd/target.go]: Please use here the project name instead of namespace name.

File: pkg/cmd/target.go [hunk 2]
```diff
@@ -200,15 +197,14 @@ func NewTargetCmd(targetReader TargetReader, targetWriter TargetWriter, configRe
...
-					os.Exit(2)
 				} else if len(shoots) == 1 {
 					targetShoot(targetWriter, shoots[0])
 				} else if len(shoots) > 1 {
-					fmt.Println("shoots:")
-					for _, val := range shoots {
-						fmt.Println("- shoot: " + val)
+					fmt.Fprintln(ioStreams.Out, "shoots:")
+					for _, shoot := range shoots {
+						fmt.Fprintln(ioStreams.Out, "- project: "+shoot.Namespace)
```
Comment (DockToFuture) [inline pkg/cmd/target.go]: Please use here the project name instead of namespace name.

File: pkg/cmd/target_test.go [hunk 3]
```diff
@@ -142,6 +142,58 @@ var _ = Describe("Target command", func() {
...
+				},
+			)
+			target.EXPECT().GardenerClient().Return(clientSet, nil)
+
+			ioStreams, _, out, _ := cmd.NewTestIOStreams()
+			command = cmd.NewTargetCmd(targetReader, targetWriter, configReader, ioStreams)
+			err := execute(command, []string{"shoot", "foo"})
+
+			Expect(err).NotTo(HaveOccurred())
+			Expect(out.String()).To(ContainSubstring("- project: garden-validation"))
```
Comment (DockToFuture) [inline pkg/cmd/target_test.go]: Please use the project name here

File: pkg/cmd/target_test.go [hunk 4]
```diff
@@ -142,6 +142,58 @@ var _ = Describe("Target command", func() {
...
+			Expect(out.String()).To(ContainSubstring("- project: garden-prod"))
```
Comment (DockToFuture) [inline pkg/cmd/target_test.go]: See above
